- name: Installing packages required for nginx
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - nginx  
    - httpd-tools

- name: Creating secure passwd for elastic user to store in nginx conf file
  ansible.builtin.expect:
    command: htpasswd -c /etc/nginx/conf.d/elastic_credentials elastic
    echo: true
    responses:
      'New password(.*)': '{{ elastic_pass }}'
      'Re-type new password(.*)': '{{ elastic_pass }}'
  ignore_errors: true

- name: Creating secure passwd for kibana user to store in nginx conf file
  ansible.builtin.expect:
    command: htpasswd  /etc/nginx/conf.d/elastic_credentials kibana_system
    echo: true
    responses:
      'New password(.*)': '{{ elastic_pass }}'
      'Re-type new password(.*)': '{{ elastic_pass }}'
  ignore_errors: true

- name: Creating cert directory on - node-6
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: elasticsearch
    mode: '750'
  with_item:
    - { {{ certs_dir }} }
    - {{ key_dir }}

- name: Copy cert file from node-5 to - rhel8-1
  ansible.builtin.copy:
    src: '/home/mahesh_hemke24/{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: '640'
  with_items:
    - { src: caa.crt , dest: '{{ certs_dir }}/{{ els_crt }}' }
    - { src: caa.key , dest: '{{ key_dir }}/{{ els_key }}' }

- name: Modifying nginx conf file on nginx (rhel8-1)
  template:
    src: templates/els_nginx.conf.j2
    dest: /etc/nginx/conf.d/els.conf
  notify: ngx restart