- name: Install Elasticsearch
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - elasticsearch
    - java-21-openjdk
    - python3-cryptography
    - expect
    - unzip
  when: ansible_hostname[0:3]|lower == 'ela'

- name: service start
  service:
    name: elasticsearch 
    state: started
    enabled: yes
  ignore_errors: true

- name: Creating cert directory
  ansible.builtin.file:
    path: '{{ certs_dir }}'
    state: directory

- name: Install pexpect package
  ansible.builtin.pip:
    name: pexpect

- name: Modifying elasticsearch.yml file on both node
  template:
    src: templates/elasticsearch3.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  when: ansible_hostname[8:14]|lower == 'node-5'

- name: Modifying elasticsearch.yml file on both node
  template:
    src: templates/elasticsearch4.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  when: ansible_hostname[8:14]|lower == 'node-6'

- name: service restart
  service:
    name: elasticsearch
    state: restarted
  ignore_errors: true
