- name: Creating cert directory on node-7
  ansible.builtin.file:
    path: '{{ ca }}'
    state: directory
    owner: root
    group: elasticsearch
    mode: '750'

- name: Copy cert file from node-5 to node-7
  ansible.builtin.copy:
    src: '/home/mahesh_hemke24/{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: elasticsearch
    mode: '640'
  with_items:
    - { src: caa.crt , dest: '{{ ca }}/caa.crt' }
    - { src: caa.key , dest: '{{ ca }}/caa.key' }
    - { src: elastic-stack-ca.p12 , dest: '{{ certs_dir }}/elastic-stack-ca.p12' }

- name: Stop elasticsearch service - node-7
  service:
    name: elasticsearch 
    state: stopped

- name: Check that the elastic-certificates.p12
  stat:
    path: /usr/share/elasticsearch/elastic-certificates.p12
  register: stat_result

### Generate a new certificate for the transport layer
- name: Import the newly created CA certificate into the Elasticsearch truststore - node-7
  ansible.builtin.expect:
    command: /usr/share/elasticsearch/bin/elasticsearch-certutil cert --ca-cert {{ certs_dir }}/ca/caa.crt --ca-key {{ certs_dir }}/ca/caa.key
    echo: true
    responses:
      'Please enter the desired output file(.*)': ''
      'Enter password for(.*)': '{{ elastic_pass }}'
  when: not stat_result.stat.exists
  ignore_errors: true
  
- name: Copy elastic-certificates.p12 file to certs directory - node-7
  ansible.builtin.copy:
    src: /usr/share/elasticsearch/elastic-certificates.p12
    dest: '{{ certs_dir }}/elastic-certificates.p12'
    owner: root
    group: elasticsearch
    mode: '640'
    remote_src: yes
      
- name: Remove the existing keystore values for the default transport keystore and truststore - node-7
  community.elastic.elastic_keystore:
    name: '{{ item }}'
    state: absent
  with_items:
    - xpack.security.transport.ssl.keystore.secure_password
    - xpack.security.transport.ssl.truststore.secure_password

- name: Add the existing keystore values for the default transport keystore and truststore - node-7
  community.elastic.elastic_keystore:
    name: '{{ item }}'
    value: '{{ elastic_pass }}'
  with_items:
    - xpack.security.transport.ssl.keystore.secure_password
    - xpack.security.transport.ssl.truststore.secure_password

- name: Modifying elasticsearch.yml file on node-7
  template:
    src: templates/els_node_7.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: 
    - els_restart

- name: FLush the handlers
  ansible.builtin.meta: flush_handlers