- name: Installing packages required for nginx on {{ ansible_hostname }}
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - nginx  
    - httpd-tools

### Creating password for els and kibana user to authenticate it to ELS and Kibana Node
- name: Creating secure passwd for elastic and kibana user to store in nginx conf file on {{ ansible_hostname }}
  ansible.builtin.expect:
    command: 
    echo: true
    responses:
      'New password(.*)': '{{ elastic_pass }}'
      'Re-type new password(.*)': '{{ elastic_pass }}'
  with_item:
    - htpasswd -c /etc/nginx/conf.d/elastic_credentials elastic
    - htpasswd /etc/nginx/conf.d/elastic_credentials kibana_system
  ignore_errors: true

### Creating conf file with proper configurations such as ports,upstrems etc.
- name: Creating nginx conf file on {{ ansible_hostname }}
  template:
    src: templates/els_nginx.conf.j2
    dest: /etc/nginx/conf.d/els.conf
  notify: 
    - ngx_restart

- name: Flush the handlers
  ansible.builtin.meta: flush_handlers