- name: enable the nginx and system module on filebeat server
  shell: | 
    - filebeat modules enable nginx
    - filebeat modules enable system

- name: Copy cert file from node-5 to - rhel8-1
  ansible.builtin.copy:
    src: '/home/mahesh_hemke24/{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: '640'
    remote_src: yes
  with_items:
    - { src: caa.crt , dest: '{{ certs_dir }}/{{ els_crt }}' }
    - { src: caa.key , dest: '{{ key_dir }}/{{ els_key }}' }
    - { src: http_ca.crt , dest: '{{ certs_dir }}/{{ els_ca_crt }}' }

- name: Modifying filebeat modulefile on nginx (rhel8-1)
  template:
    src: templates/{{ item.src }}
    dest: /etc/filebeat/modules.d/{{ item.dest }}
  with_items:
    - { src: ngx_module.j2 , dest: nginx.yml }
    - { src: sys_module.j2 , dest: system.yml }
  notify: 
    - flb_restart

- name: Setup filebeat
  shell: filebeat setup

- name: restart the filebeat service
  service: 
    name: filebeat 
    enabled: true
    state: restarted