- name: Installing packages required for nginx
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - filebeat

- name: enable system module on filebeat server
  shell: filebeat modules enable system

- name: Copy cert file from node-5 to - rhel8-1
  ansible.builtin.copy:
    src: '/home/mahesh_hemke24/{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: '640'
    remote_src: yes
  with_items:
    - { src: caa.crt , dest: '{{ certs_dir }}/{{ els_crt }}' }
    - { src: caa.key , dest: '{{ key_dir }}/{{ els_key }}' }
    - { src: http_ca.crt , dest: '{{ certs_dir }}/{{ els_ca_crt }}' }

- name: Modifying filebeat modulefile on nginx (rhel8-1)
  template:
    src: templates/{{ item.src }}
    dest: /etc/filebeat/{{ item.dest }}
  with_items:
    - { src: sys_module.j2 , dest: modules.d/system.yml }
    - { src: filebeat.yml.j2 , dest: filebeat.yml }
  notify: 
    - flb_restart

- name: FLush the handlers
  ansible.builtin.meta: flush_handlers

- name: Setup filebeat
  shell: filebeat setup

- name: restart the filebeat service
  service: 
    name: filebeat 
    enabled: true
    state: restarted