- name: Install kibana
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - kibana 
  when: ansible_hostname[8:14]|lower == 'node-5'

- name: Modifying kibana.yml file on kibana node
  template:
    src: templates/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  when: ansible_hostname[8:14]|lower == 'node-5'

- name: Kibana service stop
  service:
    name: kibana
    state: stopped
    enabled: true
  ignore_errors: true

- name: Creating a key for Kibana
  shell: openssl pkcs12 -in {{ certs_dir }}/elastic-certificates.p12 -nocerts -nodes -password pass:{{ cert_pass }}  > {{ kibana_key }}

- name: Creating a Cert for Kibana
  shell: openssl pkcs12 -in {{ certs_dir }}/elastic-certificates.p12 -clcerts -nokeys -password pass:{{ cert_pass }} > {{ kibana_cert }}

- name: Creating a ca cert for Kibana
  shell: openssl pkcs12 -in {{ certs_dir }}/elastic-certificates.p12 -cacerts -nokeys -chain -password pass:{{ cert_pass }} > {{ kibana_ca }}

- name: Kibana service start
  service:
    name: kibana
    state: restarted
  ignore_errors: true