- name: Install kibana
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - kibana 
  when: ansible_hostname[8:14]|lower == 'node-5'

- name: Kibana service start
  service:
    name: kibana
    state: started
    enabled: true
  ignore_errors: true

#### Creating Keys and certificates for Kibana
- name: Creating a key for Kibana
  shell: openssl pkcs12 -in {{ certs_dir }}/elastic-certificates.p12 -nocerts -nodes -password pass:{{ elastic_pass }}  > {{ kibana_key }}

- name: Creating a Cert for Kibana
  shell: openssl pkcs12 -in {{ certs_dir }}/elastic-certificates.p12 -clcerts -nokeys -password pass:{{ elastic_pass }} > {{ kibana_cert }}

- name: Creating a ca cert for Kibana
  shell: openssl pkcs12 -in {{ certs_dir }}/elastic-certificates.p12 -cacerts -nokeys -chain -password pass:{{ elastic_pass }} > {{ kibana_ca }}

- name: Modifying kibana.yml file on kibana node
  template:
    src: templates/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify: Kbn_restart
  when: ansible_hostname[8:14]|lower == 'node-5'

- name: FLush the handlers
  ansible.builtin.meta: flush_handlers

### Reset the kibana_system users password
- name: Reseting kibana_system users passwd
  ansible.builtin.expect:
    command: /usr/share/elasticsearch/bin/elasticsearch-reset-password -u kibana_system -i
    echo: true
    responses:
      'Please confirm that you would like to continue(.*)': 'y'
      'Enter password for(.*)': '{{ elastic_pass }}'
      'Re-enter password for(.*)': '{{ elastic_pass }}'