- name: Install kibana
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - kibana 
  when: ansible_hostname[8:14]|lower == 'node-5'

- name: Modifying kibana.yml file on kibana node
  template:
    src: templates/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  when: ansible_hostname[8:14]|lower == 'node-5'

- name: Kibana service stop
  service:
    name: kibana
    state: stopped
    enabled: true
  ignore_errors: true

- name: Creating a key for Kibana
  ansible.builtin.expect:
    command: openssl pkcs12 -in {{ certs_dir }}/elastic-certificates.p12 -nocerts -nodes  > {{ kibana_key }}
    echo: true
    responses:
      'Enter Import Password(.*)': '{{ cert_pass }}'
  ignore_errors: true

- name: Creating a Cert for Kibana
  ansible.builtin.expect:
    command: openssl pkcs12 -in {{ certs_dir }}/elastic-certificates.p12 -clcerts -nokeys  > {{ kibana_cert }}
    echo: true
    responses:
      'Enter Import Password(.*)': '{{ cert_pass }}'
  ignore_errors: true

- name: Creating a ca cert for Kibana
  ansible.builtin.expect:
    command: openssl pkcs12 -in {{ certs_dir }}/elastic-certificates.p12 -cacerts -nokeys -chain > {{ kibana_ca }}
    echo: true
    responses:
      'Enter Import Password(.*)': '{{ cert_pass }}'
  ignore_errors: true

- name: Kibana service stop
  service:
    name: kibana
    state: restarted
  ignore_errors: true